import { ThemeProvider } from '@providers/ThemeProvider'
import { Root } from '@components/Root'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider>
      <Root>
        {children}
      </Root>
    </ThemeProvider>
  )
}
